APT::FTPArchive::Release::Origin "ECTHQ";
APT::FTPArchive::Release::Label "ECTHQ";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "all amd64 i386 arm64 armhf armel riscv64 ppc64el s390x";
APT::FTPArchive::Release::Components "main";
